### ISSUE TITLE
[README]: Readme doesn't give a feel as to what the project is about

### ISSUE THREAD

**Issue by tobySolutions** [Pradumnasaraf/Snippets#11]
The readme should contain written text about what the repository is for.

The images are not so explanatory
![Screenshot from 2023-01-21 15-21-20](https://user-images.githubusercontent.com/96334363/213871069-6dd9378d-a521-4608-adce-efad3e995165.png)

**Comment by Pradumnasaraf** [comment]
Thank you for opening will do that

**Comment by tobySolutions** [comment]
Pleasure is all mine Pradumna!

**Comment by Pradumnasaraf** [comment]
Fixed in https://github.com/Pradumnasaraf/Snippets/pull/12
