### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [Pradumnasaraf/Snippets#6]
Should I add some more Git commands like git checkout...

**Comment by ShubhamJagtap2000** [comment]
> Should I add some more Git commands like git checkout...

Moreover, I see additions to Operators in "Bash" folder and 1/2 system commands as well. @Pradumnasaraf

**Comment by VenkataBhaskarr** [comment]
> Should I add some more Git commands like git checkout...

yeah this looks good.Maybe you can create a pullRequest

**Comment by ShubhamJagtap2000** [comment]
Okay, I will do.

**Comment by ShubhamJagtap2000** [comment]
Hey @VenkataBhaskarr, @Pradumnasaraf I would like to add more to Bash, especially in Bash Operators, should I continue?
